#version: "3.9"
#
#services:
#  # -----------------------------
#  # MySQL Database
#  # -----------------------------
#  mysql-db:
#    image: mysql:8.0
#    container_name: mysql-db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: centralized_data
#    ports:
#      - "33061:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - springnet
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
#      interval: 10s
#      retries: 5
#      timeout: 5s
#      start_period: 20s
#
#  # -----------------------------
#  # Keycloak Server
#  # -----------------------------
#  keycloak-server:
#    image: quay.io/keycloak/keycloak:26.2.0
#    container_name: keycloak-server
#    command: ["start-dev"]
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin@123
#    ports:
#      - "8080:8080"
#    volumes:
#      - keycloak_data:/opt/keycloak/data
#    networks:
#      - springnet
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
#      interval: 15s
#      retries: 10
#      timeout: 10s
#      start_period: 90s
#
#  # -----------------------------
#  # Project Manager Service
#  # -----------------------------
#  project-manager:
#    image: devopspaxarisglobal/product-management-service:latest
#    container_name: project-manager
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/centralized_data?allowPublicKeyRetrieval=true&useSSL=false
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SERVER_PORT: 8088
#    depends_on:
#      mysql-db:
#        condition: service_healthy
#    networks:
#      - springnet
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8088 || exit 1"]
#      interval: 15s
#      retries: 10
#      timeout: 10s
#      start_period: 60s
#
#  # -----------------------------
#  # Identity Service
#  # -----------------------------
#  identity-service:
#    image: devopspaxarisglobal/identity-service:latest
#    container_name: identity-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/centralized_data?allowPublicKeyRetrieval=true&useSSL=false
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SERVER_PORT: 8087
#      KEYCLOAK_URL: http://keycloak-server:8080
#      KEYCLOAK_REALM: master
#    depends_on:
#      mysql-db:
#        condition: service_healthy
#      keycloak-server:
#        condition: service_healthy
#      project-manager:
#        condition: service_healthy
#    networks:
#      - springnet
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8087 || exit 1"]
#      interval: 15s
#      retries: 10
#      timeout: 10s
#      start_period: 60s
#
#  # -----------------------------
#  # API Gateway
#  # -----------------------------
#  api-gateway:
#    image: devopspaxarisglobal/apigateway:latest
#    container_name: api-gateway
#    ports:
#      - "8085:8080"
#    depends_on:
#      project-manager:
#        condition: service_healthy
#      identity-service:
#        condition: service_healthy
#    networks:
#      - springnet
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
#      interval: 15s
#      retries: 10
#      timeout: 10s
#      start_period: 60s
#
## -----------------------------
## Network & Volumes
## -----------------------------
#networks:
#  springnet:
#    driver: bridge
#
#volumes:
#  mysql_data:
#  keycloak_data:
